### ISSUE TITLE
A JavaScript error occured in the browser process

### ISSUE THREAD

**Issue by zeke** [maxogden/monu#22]
This happened when I shut down a process:

![screen shot 2015-05-09 at 9 29 02 pm](https://cloud.githubusercontent.com/assets/2289/7553068/8189a72e-f692-11e4-9622-d60dab79e6e4.png)

```
Uncaught Exception:
Error: ENOENT: no such file or directory, unlink '/Users/z/Library/Application Support/Monu/data/pids/dot-clipboard.pid'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:939:18)
    at Process.removePidfiles (/Applications/Monu.app/Contents/Resources/app/node_modules/mongroup/lib/process.js:101:6)
    at null._onTimeout (/Applications/Monu.app/Contents/Resources/app/node_modules/mongroup/lib/process.js:197:10)
    at Timer.listOnTimeout (timers.js:88:15)
```

Despite the error, the process did stop as intended.

**Comment by marcbachmann** [comment]
Currently everything is based on events.
This error occurs when an event is triggered twice.
E.g. when the process isn't exiting fast enough and you click twice on the button.
